# Generated by Django 2.1 on 2018-08-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_body',
            field=models.TextField(null=True, verbose_name='断言的请求参数'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_body_AI',
            field=models.TextField(null=True, verbose_name='AI断言的请求参数'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_body_format',
            field=models.CharField(max_length=20, null=True, verbose_name='断言的请求参数格式'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_body_format_AI',
            field=models.CharField(max_length=20, null=True, verbose_name='AI断言的请求参数格式'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_head',
            field=models.TextField(null=True, verbose_name='断言的head'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_head_AI',
            field=models.TextField(null=True, verbose_name='AI断言的head'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_keywords',
            field=models.TextField(null=True, verbose_name='断言的关键字'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_keywords_is_contain',
            field=models.CharField(max_length=10, null=True, verbose_name='是否包含'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_keywords_is_contain_AI',
            field=models.CharField(max_length=10, null=True, verbose_name='是否包含'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_keywords_new_AI',
            field=models.TextField(null=True, verbose_name='AI断言的关键字'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_keywords_old',
            field=models.TextField(null=True, verbose_name='断言的关键字'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_keywords_old_AI',
            field=models.TextField(null=True, verbose_name='AI断言的关键字'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_mode',
            field=models.CharField(max_length=10, null=True, verbose_name='断言的请求方式'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_mode_AI',
            field=models.CharField(max_length=10, null=True, verbose_name='AI断言的请求方式'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_url',
            field=models.TextField(null=True, verbose_name='断言的url'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_url_AI',
            field=models.TextField(null=True, verbose_name='AI断言的url'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_use_new',
            field=models.CharField(max_length=10, null=True, verbose_name='是否使用新接口作为断言'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='assert_use_new_AI',
            field=models.CharField(max_length=10, null=True, verbose_name='是否使用新接口作为AI断言'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='body',
            field=models.TextField(null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='body_format',
            field=models.CharField(max_length=20, null=True, verbose_name='请求参数格式'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='charger',
            field=models.CharField(max_length=20, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='head',
            field=models.TextField(null=True, verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='mode',
            field=models.CharField(max_length=30, null=True, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='module',
            field=models.CharField(max_length=30, null=True, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='order',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='update_cookie',
            field=models.CharField(max_length=10, null=True, verbose_name='是否更新cookie'),
        ),
        migrations.AlterField(
            model_name='interfaces_oeasy',
            name='url',
            field=models.TextField(null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='dspt',
            field=models.TextField(null=True, verbose_name='电商平台'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='ggpt',
            field=models.TextField(null=True, verbose_name='广告平台'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='sjpt',
            field=models.TextField(null=True, verbose_name='商家平台'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='wyj',
            field=models.TextField(null=True, verbose_name='物业+'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='wypt',
            field=models.TextField(null=True, verbose_name='物业平台'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='xqmc',
            field=models.CharField(max_length=255, null=True, verbose_name='小区名称'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='yhsq',
            field=models.TextField(null=True, verbose_name='一号社区'),
        ),
        migrations.AlterField(
            model_name='public_para',
            name='yypt',
            field=models.TextField(null=True, verbose_name='运营平台'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='index',
            field=models.CharField(max_length=20, null=True, verbose_name='索引'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='keywords',
            field=models.CharField(max_length=100, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='left',
            field=models.TextField(null=True, verbose_name='左边界'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='module',
            field=models.CharField(max_length=20, null=True, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='module_id',
            field=models.CharField(max_length=20, null=True, verbose_name='模块id'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='right',
            field=models.TextField(null=True, verbose_name='右边界'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='type',
            field=models.CharField(max_length=20, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='public_para1',
            name='value',
            field=models.TextField(null=True, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='charger',
            field=models.CharField(max_length=20, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='interface_name',
            field=models.TextField(null=True, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='interface_name_display',
            field=models.TextField(null=True, verbose_name='用于展示的接口名称'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='orders',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='suit_name',
            field=models.CharField(max_length=100, null=True, verbose_name='测试套名称'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_body',
            field=models.TextField(null=True, verbose_name='断言的请求参数'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_body_format',
            field=models.CharField(max_length=20, null=True, verbose_name='断言的请求参数格式'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_head',
            field=models.TextField(null=True, verbose_name='断言的head'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_keywords',
            field=models.TextField(null=True, verbose_name='断言的关键字'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_keywords_is_contain',
            field=models.CharField(max_length=10, null=True, verbose_name='是否包含'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_keywords_old',
            field=models.TextField(null=True, verbose_name='断言的关键字'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_mode',
            field=models.CharField(max_length=10, null=True, verbose_name='断言的请求方式'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_url',
            field=models.TextField(null=True, verbose_name='断言的url'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='assert_use_new',
            field=models.CharField(max_length=10, null=True, verbose_name='是否使用新接口作为断言'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='body',
            field=models.TextField(null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='body_format',
            field=models.CharField(max_length=20, null=True, verbose_name='请求参数格式'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='head',
            field=models.TextField(null=True, verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='interface_name',
            field=models.CharField(max_length=100, null=True, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='mode',
            field=models.CharField(max_length=10, null=True, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='suit_id',
            field=models.IntegerField(null=True, verbose_name='测试套id'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='suit_name',
            field=models.CharField(max_length=100, null=True, verbose_name='测试套名称'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='update_cookie',
            field=models.CharField(max_length=10, null=True, verbose_name='是否更新cookie'),
        ),
        migrations.AlterField(
            model_name='suit_interface',
            name='url',
            field=models.TextField(null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='suit_result',
            name='date_time',
            field=models.CharField(max_length=20, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='suit_result',
            name='response',
            field=models.TextField(null=True, verbose_name='响应信息'),
        ),
        migrations.AlterField(
            model_name='suit_result',
            name='result',
            field=models.CharField(max_length=20, null=True, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='suit_result',
            name='suit_id',
            field=models.IntegerField(null=True, verbose_name='测试套id'),
        ),
        migrations.AlterField(
            model_name='suit_result',
            name='suit_interface_id',
            field=models.IntegerField(null=True, verbose_name='接口id'),
        ),
    ]
