# Generated by Django 2.1 on 2018-08-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_interface', '0002_auto_20180808_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='suit_interface',
            name='interface_testresult',
            field=models.IntegerField(null=True),
        ),
    ]
